__default__:
  memory: 5000
  n: 1
  name: "{rule}.{wildcards}"
  output: "/hps/nobackup/birney/users/ian/somites/log/{rule}_{wildcards}.out"
  error: "/hps/nobackup/birney/users/ian/somites/log/{rule}_{wildcards}.err"
map_reads:
  memory: 20000
  n: 4