__default__:
  memory: 5000
  n: 1
  name: "{rule}.{wildcards}"
  queue: "standard"
  outfile: "{log}"
copy_f2_seq_data:
  queue: "datamover"
bwa_mem2_index:
  memory: {resources.mem_mb}
map_reads_F0:
  memory: "{resources.mem_mb}"
  n: "{threads}"
replace_rg_F0:
  memory: "{resources.mem_mb}"
sort_sam_F0:
  memory: "{resources.mem_mb}"
mark_duplicates_F0:
  memory: "{resources.mem_mb}"
haplotype_caller:
  memory: "{resources.mem_mb}"
bwa_mem2_mem:
  memory: 10000
  n: 8
replace_rg_f2:
  memory: 20000
sort_sam_f2:
  memory: 20000
bam_readcount:
  memory: 10000
make_dp_AB:
  memory: 10000
run_rc_block:
    memory: 50000
bam_readcount_F0:
  memory: 10000