samples:
    config/samples.txt
groups:
    - "1"
    - "2"
#units:
#    config/units.txt

ref:
    # ensembl species name
    species: oryzias_latipes
    # ensembl release
    release: 104
    # genome build
    build: ASM223467v1
ref_path:
    "/hps/nobackup/birney/users/ian/somites/refs/hdrr.fasta"
raw_data_dir:
    "/hps/nobackup/birney/projects/indigene/raw_data"
working_dir:
    "/hps/nobackup/birney/users/ian/somites"
log_dir:
    "/hps/nobackup/birney/users/ian/somites/log"

params:
    minimap2:
        threads: 4
    gatk:
        HaplotypeCaller: ""
        BaseRecalibrator: ""
        GenotypeGVCFs: ""
        VariantRecalibrator: ""
    picard:
        MarkDuplicates: "REMOVE_DUPLICATES=true"
    trimmomatic:
        pe:
        trimmer:
            # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
            - "LEADING:3"
            - "TRAILING:3"
            - "SLIDINGWINDOW:4:15"
            - "MINLEN:36"
