samples:
    config/samples.txt
F2_samples:
    config/F2_samples.txt
F2_valid_lanes:
    config/F2_valid_lanes.txt
groups:
    - "1"
    - "2"
contigs:
    - 1
    - 24

ref:
    # ensembl species name
    species: oryzias_latipes
    # ensembl release
    release: 104
    # genome build
    build: ASM223467v1
ref_prefix:
    "/hps/nobackup/birney/users/ian/somites/refs/hdrr"
raw_data_dir:
    "/hps/nobackup/birney/projects/indigene/raw_data"
working_dir:
    "/hps/nobackup/birney/users/ian/somites"
tmp_dir:
    "/hps/nobackup/birney/users/ian/somites/tmp"



