project:
  type: book
  output-dir: "../docs"

#book_filename: "book"
#new_session: yes
#before_chapter_script: _common.R
#delete_merged_file: true
#language:
#  ui:
#    chapter_name: "Chapter "

highlight-style: atom-one

book:
  title: "Somite periodicity notebook"
  author: "Ian Brettell"
  date: today
  date-format: "D MMMM YYYY"
  csl: chicago-fullnote-bibliography.csl
  number-sections: true
  search: true
  repo-url: https://github.com/brettellebi/somites
  repo-subdir: book
  repo-branch: master
  repo-actions: [edit]
  chapters:
    - index.qmd
    - 01-background.qmd
    - 02-phenotypes.qmd
    - 03-F0-homozygosity.qmd
    - 04-F1-heterozygosity.qmd
    - 05-F2-genotyping.qmd
    - 06-GWAS.qmd
    - 07-references.qmd

format:
  html:
    toc: true
    toc-title: "On this page"
    theme: zephyr
    fontsize: 0.95em
    bibliography: book.bib
    linkcolor: "#3C1642"
    code-fold: true
    #backgroundcolor: "#3C1642"

#  - "01-Data_processing_with_Snakemake.Rmd",
#  - "02-F0_homozygosity.Rmd",
#  - "03-1-F2_recombination_all_sites.Rmd",
#  - "03-5-F2_recombination_no_repeat_reads_or_pers_hets_filtered_for_read_count_and_cab_prop.Rmd",
#  - "04-1-Phenotype_exploration.Rmd",
#  - "04-2-Test_GWAS_code.Rmd",
#  - "05-GWLS_results.Rmd",
#  - "Period_intercept_with_AU.Rmd",
#  - "Period_intercept_with_DB.Rmd",
#  - "Inverse_normalise_by_microscope.Rmd",
#  - "Reporter_as_covariate.Rmd",
#  - "08-Annotations.Rmd",
#  - "07-references.Rmd"