project:
  type: book
  output-dir: "../docs"

highlight-style: atom-one

book:
  title: "Somite periodicity notebook"
  author: "Ian Brettell"
  date: today
  date-format: "D MMMM YYYY"
  #csl: chicago-fullnote-bibliography.csl
  #number-sections: true
  search: true
  repo-url: https://github.com/brettellebi/somites
  repo-subdir: book
  repo-branch: master
  repo-actions: [edit]
  chapters:
    - index.qmd
    - 01-background.qmd
    - 02-phenotypes.qmd
    - 03-F0-homozygosity.qmd
    - 04-F1-heterozygosity.qmd
    - 05-F2-genotyping.qmd
    - 06-GWAS.qmd
    - 07-references.qmd

format:
  html:
    toc: true
    toc-title: "On this page"
    theme: zephyr
    fontsize: 0.95em
    bibliography: book.bib
    linkcolor: "#3C1642"
    code-fold: true
    csl: chicago-fullnote-bibliography.csl
    #backgroundcolor: "#3C1642"
